accounts/urls.py
from django.urls import path

from  accounts.views import (
    LogInView, LogOutView, SignUpView, ActivateView,
)

app_name = "accounts"

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
import os
from django.views.generic.base import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
    path('', TemplateView.as_view(template_name='home/index.html'), name = "index"),
    
]

home/views.py
from django.shortcuts import render

# Create your views here.

home/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sample Django Project to demonstrate basic user functionality.">
        <meta name="author" content="Shivateja Burle">
        <title>{% block title %}{% endblock %}</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="icon" type="image/png" href="{% static 'home/favicon.ico' %}">
    </head>
    <body>
        {% block navbar %}
            {% include "menu.html" %}
        {% endblock %}
        <div class="container mt-3">
            {% bootstrap_messages %}
        </div>
        {% block content %}
        {% endblock %}
        <script>
            function setActive(){
                if ("{{request.resolver_match.route}}") {
                    document.getElementById("{{request.resolver_match.route}}").classList.add('active');
                } else {
                    document.getElementById("home").classList.add('active');
                }
            }
            setActive();
        </script>
    </body>
</html>

home/templates/menu.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Django User Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a id="home" class="nav-link" aria-current="page" href="/">Home</a>
                </li>                
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="{% url 'admin:login' %}">Django Administration</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:log_out' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:log_in' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>